-- Webshop Database Seeds (Sample Data)

USE webshop;

-- Insert sample users
INSERT INTO users (name, username) VALUES
('John Doe', 'john_doe'),
('Jane Smith', 'jane_smith'),
('Mike Johnson', 'mike_j'),
('Sarah Williams', 'sarah_w'),
('Tom Brown', 'tom_brown'),
('Alex Chen', 'alex_chen'),
('Emily Davis', 'emily_d'),
('Robert Garcia', 'rob_g'),
('Lisa Wang', 'lisa_wang'),
('David Miller', 'david_m'),
('Maria Rodriguez', 'maria_r'),
('James Wilson', 'j_wilson'),
('Sophia Lee', 'sophia_lee'),
('Daniel Taylor', 'dan_t'),
('Olivia Martinez', 'olivia_m'),
('Chris Thompson', 'chris_t'),
('Amanda Harris', 'amanda_h'),
('Kevin Clark', 'kevin_c'),
('Jessica Lewis', 'jessica_l'),
('Brian Robinson', 'brian_r'),
('Nicole Walker', 'nicole_w'),
('Jason Allen', 'jason_a'),
('Michelle Young', 'michelle_y'),
('Steven King', 'steven_k'),
('Rebecca Scott', 'rebecca_s'),
('Paul Green', 'paul_g'),
('Megan Adams', 'megan_a'),
('Joshua Nelson', 'joshua_n'),
('Kimberly Hall', 'kimberly_h'),
('Andrew Baker', 'andrew_b'),
('Samantha Carter', 'samantha_c'),
('Matthew Perez', 'matthew_p'),
('Elizabeth Torres', 'elizabeth_t'),
('Ryan Evans', 'ryan_e'),
('Victoria Phillips', 'victoria_p'),
('Jacob Turner', 'jacob_t'),
('Julia Collins', 'julia_c'),
('Benjamin Stewart', 'benjamin_s'),
('Catherine Parker', 'catherine_p'),
('Patrick Edwards', 'patrick_e'),
('Danielle Morris', 'danielle_m'),
('Timothy Rivera', 'timothy_r'),
('Brittany Cook', 'brittany_c'),
('Nathan Cooper', 'nathan_c'),
('Alexis Reed', 'alexis_r'),
('Peter Bailey', 'peter_b'),
('Vanessa Bell', 'vanessa_b'),
('Jonathan Gray', 'jonathan_g'),
('Monica Howard', 'monica_h'),
('Shawn Ward', 'shawn_w'),
('Tiffany Cox', 'tiffany_c'),
('Philip Diaz', 'philip_d'),
('Jasmine Foster', 'jasmine_f'),
('Brandon Brooks', 'brandon_b'),
('Chelsea Price', 'chelsea_p'),
('Marcus Wood', 'marcus_w'),
('Gina Ross', 'gina_r'),
('Kenneth Bennett', 'kenneth_b'),
('Heather Hughes', 'heather_h'),
('Raymond Barnes', 'raymond_b'),
('April Fisher', 'april_f'),
('Derek Henderson', 'derek_h'),
('Natalie Coleman', 'natalie_c'),
('Victor Jenkins', 'victor_j'),
('Molly Patterson', 'molly_p');


INSERT INTO products (name, price, click, description) VALUES
('Lorum Epsum lang test', 79.99, 150, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Nullam nulla eros, ultricies sit amet, nonummy id, imperdiet feugiat, pede. Sed lectus. Donec mollis hendrerit risus. Phasellus nec sem in justo pellentesque facilisis. Etiam imperdiet imperdiet orci. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu. Phasellus accumsan cursus velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue, elit erat euismod orci, ac placerat dolor lectus quis orci. Phasellus consectetuer vestibulum elit. Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc. Vestibulum fringilla pede sit amet augue. In turpis. Pellentesque posuere. Praesent turpis. Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus. Donec elit libero, sodales nec, volutpat a, suscipit non, turpis. Nullam sagittis. Suspendisse pulvinar, augue ac venenatis condimentum, sem libero volutpat nibh, nec pellentesque velit pede quis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus. Ut varius tincidunt libero. Phasellus dolor. Maecenas vestibulum mollis diam. Pellentesque ut neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium. Pellentesque auctor neque nec urna. Proin sapien ipsum, porta a, auctor quis, euismod ut, mi. Aenean viverra rhoncus pede. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut non enim eleifend felis pretium feugiat. Vivamus quis mi. Phasellus a est. Phasellus magna. In hac habitasse platea dictumst. Curabitur at lacus ac velit ornare lobortis. Curabitur a felis in nunc fringilla tristique. Morbi mattis ullamcorper velit. Phasellus gravida semper nisi. Nullam vel sem. Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec, quam. Sed hendrerit. Morbi ac felis. Nunc egestas, augue at pellentesque laoreet, felis eros vehicula leo, at malesuada velit leo quis pede. Donec interdum, metus et hendrerit aliquet, dolor diam sagittis ligula, eget egestas libero turpis vel mi. Nunc nulla. Fusce'),
('Wireless Headphones', 79.99, 150, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec q'),
('Smart Watch', 249.99, 320, 'Fitness tracking smartwatch with heart rate monitor and GPS'),
('Laptop Stand', 34.99, 89, 'Ergonomic aluminum laptop stand for better posture'),
('USB-C Hub', 45.99, 210, '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader'),
('Mechanical Keyboard', 129.99, 275, 'RGB backlit mechanical keyboard witxh blue switches'),
('Portable SSD', 159.99, 180, '1TB portable SSD with fast read/write speeds'),
('Webcam 1080p', 69.99, 95, 'Full HD webcam with auto-focus and built-in microphone'),
('Phone Case', 19.99, 420, 'Shockproof protective phone case with kickstand'),
('Bluetooth Speaker', 89.99, 165, 'Waterproof Bluetooth speaker with 12-hour playtime'),
('Wireless Mouse', 29.99, 340, 'Ergonomic wireless mouse with adjustable DPI'),
('Gaming Monitor 27"', 349.99, 45, '27-inch QHD gaming monitor with 144Hz refresh rate'),
('Desk Lamp LED', 39.99, 12, 'Adjustable LED desk lamp with touch controls and USB charging port'),
('Cable Management Kit', 14.99, 8, 'Complete cable organizer set for clean desk setup'),
('Laptop Cooling Pad', 24.99, 31, 'Dual fan cooling pad with adjustable height for laptops up to 17 inches'),
('Smartphone Gimbal', 99.99, 72, '3-axis handheld gimbal stabilizer for smartphones'),
('External Hard Drive 2TB', 89.99, 54, 'Portable external hard drive with USB 3.0 connectivity'),
('Wireless Charger Stand', 39.99, 210, 'Fast wireless charging stand compatible with Qi devices'),
('Action Camera 4K', 199.99, 33, 'Waterproof action camera with 4K video and image stabilization'),
('Ergonomic Keyboard Wrist Rest', 19.99, 145, 'Memory foam wrist rest for ergonomic keyboard support'),
('Smartphone Screen Protector', 12.99, 298, 'Tempered glass screen protector with anti-scratch coating'),
('HDMI Cable 6ft', 9.99, 412, 'High-speed HDMI cable supporting 4K resolution and HDR'),
('Laptop Sleeve 15.6"', 24.99, 134, 'Water-resistant laptop sleeve with padded interior'),
('USB Flash Drive 128GB', 29.99, 256, 'High-speed USB 3.0 flash drive with durable metal casing'),
('Wireless Earbuds', 59.99, 198, 'True wireless earbuds with charging case and touch controls'),
('Monitor Mount Arm', 79.99, 67, 'Adjustable monitor mount arm for single or dual monitors'),
('Gaming Keyboard and Mouse Combo', 89.99, 123, 'RGB backlit gaming keyboard and mouse combo set'),
('Smartphone Car Mount', 19.99, 345, 'Universal car mount holder for smartphones with 360-degree rotation'),
(' Laptop Docking Station', 149.99, 42, 'Multi-port laptop docking station with dual monitor support'),
('Gaming Laptop 15"', 1299.99, 87, 'High-performance gaming laptop with RTX 4070, 32GB RAM, and 1TB SSD'),
('Noise Cancelling Headphones Pro', 299.99, 142, 'Premium over-ear headphones with adaptive noise cancellation and 30-hour battery'),
('Smart Fitness Band', 79.99, 256, 'Water-resistant fitness tracker with heart rate monitor and sleep tracking'),
('Wireless Earbuds Sport', 119.99, 198, 'Sweat-proof wireless earbuds with secure fit and 8-hour battery life'),
('4K Ultra HD TV 55"', 649.99, 54, 'Smart TV with HDR10+, streaming apps, and voice remote'),
('Electric Kettle Smart', 59.99, 121, 'Temperature-controlled smart kettle with app connectivity'),
('Portable Projector', 279.99, 78, 'Compact HD projector with built-in speakers and streaming capabilities'),
('Ergonomic Vertical Mouse', 49.99, 165, 'Vertical ergonomic mouse to reduce wrist strain and improve posture'),
('Multi-Port Charging Station', 74.99, 189, '6-port charging station with fast charging for multiple devices'),
('Smart Light Bulbs 4-Pack', 44.99, 232, 'Color-changing smart bulbs compatible with voice assistants'),
('Air Fryer Digital', 89.99, 95, '5-quart digital air fryer with touch controls and preset cooking modes'),
('Bluetooth Car Adapter', 29.99, 310, 'Wireless Bluetooth adapter for cars with hands-free calling'),
('Professional Microphone', 129.99, 67, 'USB condenser microphone for streaming, podcasting, and recording'),
('Adjustable Dumbbell Set', 349.99, 42, 'Space-saving adjustable dumbbells from 5-50 lbs per dumbbell'),
('Electric Toothbrush', 89.99, 178, 'Sonic electric toothbrush with multiple modes and smart timer'),
('Laptop Backpack', 64.99, 134, 'Water-resistant laptop backpack with charging port and organizer pockets'),
('Smart Scale', 49.99, 89, 'Wi-Fi connected body composition scale with app tracking'),
('Cordless Drill Kit', 129.99, 56, '20V cordless drill and driver kit with 2 batteries and carrying case'),
('Indoor Security Camera', 99.99, 156, '1080p indoor security camera with motion detection and night vision'),
('Wireless Presenter', 39.99, 72, 'Professional wireless presenter with laser pointer and slide control'),
('Compact Blender', 49.99, 112, 'Personal-sized blender for smoothies and shakes with travel lid'),
('Reading E-Reader', 139.99, 88, '6-inch e-reader with adjustable warm light and weeks of battery life'),
('Yoga Mat Premium', 34.99, 201, 'Non-slip yoga mat with alignment lines and carrying strap'),
('Coffee Maker Programmable', 79.99, 143, '12-cup programmable coffee maker with thermal carafe'),
('Fitness Smart Jump Rope', 49.99, 91, 'Smart jump rope with app tracking for workouts and calorie counting'),
('Phone Gimbal Stabilizer', 99.99, 67, '3-axis smartphone gimbal for smooth video recording'),
('Portable Power Station', 299.99, 45, '300W portable power station for camping and emergencies'),
('Heated Blanket Queen', 69.99, 124, 'Machine washable heated blanket with multiple heat settings'),
('Gaming Chair Pro', 349.99, 38, 'Ergonomic gaming chair with lumbar support and adjustable armrests'),
('Waterproof Bluetooth Shower Speaker', 34.99, 267, 'Suction cup shower speaker with 8-hour battery life'),
('Digital Meat Thermometer', 29.99, 89, 'Wireless digital meat thermometer with smartphone app'),
('Car Vacuum Cleaner', 59.99, 112, 'Portable car vacuum with multiple attachments and LED light'),
('Resistance Band Set', 24.99, 189, '5-piece resistance band set for home workouts and strength training'),
('Aromatherapy Diffuser', 39.99, 156, 'Ultrasonic essential oil diffuser with color changing lights'),
('Gaming Mouse Pad XL', 29.99, 234, 'Extra-large gaming mouse pad with waterproof surface and stitched edges'),
('Insulated Tumbler 30oz', 34.99, 278, 'Double-wall insulated tumbler with straw lid and non-slip base'),
('Phone Tripod Mount', 19.99, 321, 'Adjustable phone tripod with Bluetooth remote for photos and videos'),
('Electric Back Massager', 79.99, 76, 'Shiatsu back massager with heat function for neck and shoulders'),
('Digital Drawing Tablet', 89.99, 54, '10-inch drawing tablet with pressure-sensitive pen for digital art'),
('Bike Phone Mount', 24.99, 145, 'Secure universal bike phone mount with 360-degree rotation'),
('UV Phone Sanitizer', 49.99, 98, 'UV-C light phone sanitizer with wireless charging capability'),
('Adjustable Laptop Table', 89.99, 67, 'Bedside laptop table with adjustable height and cooling fan'),
('Smart Plant Monitor', 39.99, 56, 'Smart sensor that monitors plant soil moisture, light, and temperature'),
('Car Jump Starter', 129.99, 43, 'Portable car jump starter with air compressor and power bank features'),
('Reusable Silicone Food Bags', 19.99, 187, 'Eco-friendly silicone food storage bags in multiple sizes'),
('Posture Corrector', 29.99, 132, 'Adjustable posture corrector for back pain relief and alignment'),
('Magnetic Phone Car Mount', 21.99, 289, 'Strong magnetic car phone mount with 360-degree rotation'),
('Collapsible Water Bottle', 17.99, 156, 'BPA-free collapsible water bottle for travel and outdoor activities'),
('Phone Camera Lens Kit', 45.99, 87, 'Clip-on phone camera lens kit with wide angle, macro, and fisheye lenses'),
('Electric Nail File Kit', 34.99, 123, 'Professional electric nail file with multiple attachments and speeds'),
('Sleep Mask with Bluetooth', 49.99, 94, 'Bluetooth sleep mask with built-in speakers for bedtime listening'),
('Portable Espresso Maker', 89.99, 65, 'Manual portable espresso maker for camping and travel'),
('Smart Door Lock', 199.99, 52, 'Keyless smart door lock with fingerprint and code entry'),
('Himalayan Salt Lamp', 28.99, 176, 'Natural Himalayan salt lamp with dimmer switch and wooden base'),
('Water Flosser Electric', 69.99, 87, 'Cordless water flosser with multiple pressure settings and tips'),
('Folding Laptop Stand', 39.99, 134, 'Portable aluminum folding laptop stand for travel and work'),
('Car Seat Gap Filler', 14.99, 201, 'Organizer that prevents items from falling between car seats'),
('Memory Foam Seat Cushion', 44.99, 145, 'Orthopedic memory foam seat cushion for office and car use'),
('UV Sunglasses Aviator', 22.99, 278, 'Polarized UV protection sunglasses with multiple color options'),
('Cord Organizer Box', 32.99, 89, 'Decorative cord organizer box to hide power strips and cables'),
('Keyboard Cleaning Gel', 12.99, 312, 'Reusable cleaning gel for keyboards and electronics'),
('Gaming Controller Charger', 29.99, 167, 'Dual charging station for gaming controllers with LED indicators'),
('Waterproof Phone Pouch', 16.99, 189, 'Transparent waterproof phone pouch for swimming and beach activities'),
('Smart Pet Feeder', 129.99, 56, 'Automatic pet feeder with portion control and scheduling app'),
('LED Strip Lights 16.4ft', 24.99, 287, 'Color-changing LED strip lights with remote control and app'),
('Neck Fan Portable', 39.99, 112, 'Hands-free neck fan with 3 speed settings and quiet operation'),
('Electric Can Opener', 29.99, 78, 'Automatic electric can opener with smooth edge technology'),
('Camping Hammock Double', 49.99, 95, 'Portable camping hammock with tree straps and carrying bag'),
('Facial Steamer Nano', 45.99, 67, 'Portable nano ionic facial steamer for skincare routine'),
('Shoe Dryer Boot', 69.99, 54, 'Electric shoe dryer and deodorizer for boots and shoes'),
('Digital Luggage Scale', 24.99, 123, 'Portable digital luggage scale with backlit LCD display'),
('Mini Waffle Maker', 29.99, 145, 'Single serve mini waffle maker for quick breakfasts'),
('Car Windshield Sun Shade', 21.99, 187, 'Custom-fit windshield sun shade with storage bag'),
('Rechargeable Hand Warmer', 34.99, 132, 'Dual-purpose hand warmer and power bank with 3 heat settings'),
('Spice Jar Organizer Set', 39.99, 98, 'Magnetic spice jar set with labels and organizing rack'),
('Telescoping Back Scratcher', 14.99, 176, 'Extendable back scratcher with multiple scratching surfaces'),
('Golf Swing Trainer', 89.99, 45, 'Smart golf swing analyzer with real-time feedback'),
('Aquarium Automatic Feeder', 35.99, 67, 'Programmable fish feeder for vacation and daily use'),
('Ice Roller for Face', 24.99, 189, 'Reusable ice roller for reducing puffiness and facial massage'),
('Portable White Noise Machine', 42.99, 112, 'Travel white noise machine with multiple soothing sounds'),
('Herb Garden Indoor Kit', 34.99, 145, 'Indoor hydroponic herb garden with LED grow lights'),
('Posture Correction Brace', 39.99, 134, 'Adjustable upper back posture corrector with breathable material'),
('Electric Wine Opener', 34.99, 98, 'Rechargeable electric wine opener with foil cutter'),
('Laptop Privacy Screen Filter', 64.99, 76, 'Anti-glare privacy filter for laptop screens'),
('Adjustable Pillow Stand', 49.99, 89, 'Adjustable pillow stand for reading and tablet use in bed'),
('Car Emergency Kit', 59.99, 67, 'Comprehensive car emergency kit with first aid and tools'),
('Digital Recipe Book Stand', 29.99, 123, 'Adjustable recipe book stand with tablet holder and page clips'),
('Ergonomic Office Chair', 289.99, 75, 'Adjustable lumbar support office chair with breathable mesh back'),
('Noise Cancelling Earbuds', 149.99, 220, 'True wireless earbuds with active noise cancellation and 24-hour battery'),
('4K Action Camera', 329.99, 65, 'Waterproof action camera with 4K/60fps video and image stabilization'),
('Electric Standing Desk', 449.99, 42, 'Height adjustable electric standing desk with memory presets'),
('Smart Home Hub', 89.99, 178, 'Central controller for smart home devices with voice assistant support'),
('Ultrawide Monitor 34"', 699.99, 38, '34-inch curved ultrawide monitor with 1440p resolution and 120Hz refresh'),
('Gaming Headset', 129.99, 195, '7.1 surround sound gaming headset with retractable microphone'),
('Wireless Charging Pad', 29.99, 310, 'Fast wireless charger compatible with Qi-enabled devices'),
('External Battery Pack', 49.99, 128, '20000mAh power bank with USB-C PD and quick charge support'),
('Document Scanner', 179.99, 56, 'Automatic document feeder scanner with OCR software included'),
('Dash Cam Front/Rear', 199.99, 84, 'Dual channel dash cam with parking mode and GPS logging'),
('Air Purifier', 159.99, 47, 'HEPA air purifier with smart sensors for home or office use'),
('Smart Doorbell', 249.99, 92, 'Video doorbell with motion detection and two-way audio'),
('Robot Vacuum', 449.99, 67, 'Smart mapping robot vacuum with self-emptying base station'),
('Smart Thermostat', 199.99, 54, 'WiFi-enabled smart thermostat with energy-saving features and app control'),
('3D Printer', 499.99, 22, 'Desktop 3D printer with auto-leveling and silent stepper motors'),
('Wireless Security Camera', 129.99, 87, 'Outdoor wireless security camera with night vision and cloud storage'),
('Electric Toothbrush', 59.99, 134, 'Rechargeable electric toothbrush with multiple cleaning modes'),
('Fitness Tracker', 79.99, 201, 'Slim fitness tracker with heart rate and sleep monitoring'),
('Portable Projector', 299.99, 33, 'Mini portable projector with HDMI and built-in speakers'),
('Smart Light Bulb', 24.99, 145, 'Color-changing LED smart bulb with voice control'),
('Noise Meter', 39.99, 18, 'Digital sound level meter for home and professional use'),
('Electric Kettle', 49.99, 76, 'Stainless steel electric kettle with temperature presets'),
('Wireless Router', 159.99, 112, 'Dual-band WiFi 6 router with parental controls and guest network');




INSERT INTO product_reviews (product_id, user_id, text, score) VALUES
(1, 1, 'Amazing sound quality! Very comfortable for long listening sessions.', 5),
(1, 2, 'Good headphones but a bit pricey. Battery life is excellent though.', 4),
(1, 3, 'Best headphones I have ever owned. Worth every penny!', 5),
(1, 5, 'Noise cancellation is superb. Perfect for commuting!', 5),
(2, 2, 'Great smartwatch with accurate fitness tracking.', 5),
(2, 4, 'Good device but the battery could be better.', 3),
(2, 5, 'Love all the health features. Syncs perfectly with my phone.', 4),
(3, 1, 'Perfect height for my setup. Very sturdy and well-made.',2),
(3, 5, 'Nice stand but wish it was adjustable.', 4),
(3, 2, 'Great build quality. Really helps with my neck pain.', 5),
(4, 3, 'Essential hub for my laptop. All ports work flawlessly.', 5),
(4, 1, 'Good quality hub, no issues so far.', 4),
(4, 4, 'Works great but gets a bit warm during heavy use.', 4),
(5, 4, 'Love the feel of mechanical keys. RGB lighting is beautiful.', 1),
(5, 2, 'Great keyboard but quite loud. Not ideal for shared spaces.', 1),
(5, 3, 'Amazing typing experience. Very responsive switches.', 5),
(5, 1, 'Best keyboard for gaming and coding. Highly recommend!', 5),
(6, 5, 'Super fast transfer speeds. Very portable and durable.', 5),
(6, 2, 'Excellent SSD. Perfect for video editing on the go.', 5),
(7, 3, 'Clear video quality and easy to set up.', 4),
(7, 1, 'Works well for video calls. Good value for money.', 4),
(7, 5, 'Sharp image quality. Autofocus works perfectly.', 5),
(8, 2, 'Protects my phone well and looks great!', 5),
(8, 4, 'Decent case but kickstand feels a bit flimsy.', 3),
(9, 5, 'Amazing sound for its size. Perfect for outdoor use.', 5),
(9, 3, 'Good speaker but not as loud as I expected.', 4),
(9, 1, 'Waterproof feature is great. Takes it to the beach all the time!', 5),
(9, 2, 'Clear sound and deep bass. Battery life is impressive.', 4),
(10, 1, 'Very comfortable mouse, works on any surface.', 5),
(10, 4, 'Good mouse for the price. Battery lasts a long time.', 4),
(10, 3, 'Ergonomic design prevents wrist strain. Love it!', 5),
(75, 12, 'Perfect for travel! Folds down incredibly small and lightweight.', 5),
(75, 28, 'Sturdy construction, works on any surface. Great value!', 5),
(76, 45, 'Strong suction, phone stays in place even on bumpy roads.', 5),
(76, 9, '360 rotation is smooth and holds position well.', 5),
(77, 33, 'Phone feels truly clean after sanitizing cycle. Love the wireless charging feature!', 5),
(77, 57, 'Quick and effective. Easy to use daily.', 4),
(78, 21, 'Perfect height adjustment for working in bed. The fan is surprisingly quiet.', 4),
(78, 64, 'Sturdy construction, doesn''t wobble even with my heavy gaming laptop.', 5),
(79, 5, 'Saved my houseplants from overwatering! Accurate moisture readings.', 5),
(79, 41, 'App notifications are timely. Easy setup with Bluetooth.', 1),
(80, 18, 'Started my dead car battery in seconds. Lifesaver on road trips.', 5),
(80, 52, 'The air compressor works well for topping up tires. Multi-functional device.', 4),
(81, 25, 'Eco-friendly and durable. Dishwasher safe is a huge plus.', 2),
(81, 37, 'Good seal keeps vegetables fresh longer. Multiple sizes are convenient.', 5),
(82, 60, 'Helped correct my slouching habit. Adjustable straps make it comfortable.', 4),
(82, 14, 'Noticeable improvement in back pain after wearing it during work.', 5),
(83, 49, 'Holds phone securely even on rough terrain. Magnetic mount is strong.', 5),
(83, 3, 'One-handed operation is smooth. Rotation allows perfect viewing angle.', 3),
(84, 31, 'Folds to pocket-size! No leaks after months of daily use.', 5),
(84, 8, 'Perfect for hiking and gym. Lightweight and durable.', 5),
(85, 22, 'Wide angle lens captures beautiful landscapes. Macro lens is surprisingly sharp.', 5),
(85, 46, 'Easy to clip on and off. Protective case keeps lenses safe.', 4),
(86, 11, 'Professional results at home. Multiple speed settings for different nail types.', 5),
(86, 59, 'Quiet operation, battery lasts through multiple uses.', 5),
(87, 34, 'Stays on most of the night. Sound quality is decent for sleep sounds.', 3),
(87, 7, 'Bluetooth connection is stable. Helps me fall asleep with white noise.', 4),
(88, 50, 'Makes surprisingly good espresso without electricity! Perfect for camping.', 5),
(88, 16, 'Learning curve to get the grind right, but worth it for portable espresso.', 4),
(89, 27, 'Installation took 30 minutes. Fingerprint recognition is fast and accurate.', 5),
(89, 43, 'Temporary codes for guests work perfectly. App is user-friendly.', 5),
(90, 6, 'Creates a warm, cozy atmosphere. Dimmer allows perfect brightness control.', 5),
(90, 39, 'Natural salt lamp, beautiful glow. Well-made with wooden base.', 5),
(91, 20, 'More effective than traditional floss for me. Multiple pressure settings help.', 5),
(91, 55, 'Cordless design is convenient. Easy to fill and clean.', 4),
(92, 13, 'Folds completely flat for travel. Sturdy enough for my 15" laptop.', 5),
(92, 48, 'Angle adjustment is smooth. The cooling fan helps on hot days.', 4),
(93, 29, 'Prevents my phone from disappearing between seats! Easy to install.', 5),
(93, 62, 'Also provides extra storage for small items. Very practical.', 5),
(94, 2, 'Relieves pressure during long commutes. Memory foam is comfortable.', 5),
(94, 35, 'Non-slip bottom keeps it in place. Washable cover is convenient.', 5),
(95, 24, 'Polarized lenses work great for driving. Multiple color options are nice.', 5),
(95, 58, 'Good UV protection. Comfortable to wear for extended periods.', 4),
(96, 10, 'Hides all my cables neatly! Looks clean and organized.', 5),
(96, 53, 'Easy to access outlets when needed. Ventilation is good.', 5),
(97, 40, 'Fun to use and cleans keyboards effectively. Reusable many times.', 5),
(97, 17, 'Gets into tight spaces between keys. Satisfying to use.', 5),
(98, 63, 'Charges both controllers simultaneously. LED indicators are helpful.', 5),
(98, 26, 'No more searching for charging cables. Dock is stable.', 5),
(99, 4, 'Perfect for beach vacations! Phone stays completely dry.', 5),
(99, 47, 'Touchscreen works through the pouch. Great for pool photos.', 4),
(100, 32, 'Feeds my cats perfectly while I''m away. App scheduling works reliably.', 5),
(100, 15, 'Portion control is accurate. Cats adapted to it quickly.', 5),
(101, 1, 'LED strips are bright and colors are vibrant. Remote control works well.', 5),
(101, 44, 'Easy to cut to length. Adhesive backing sticks well to surfaces.', 4),
(102, 19, 'Hands-free cooling is amazing for summer walks. Quiet operation.', 5),
(102, 56, 'Three speed settings are sufficient. Battery lasts as advertised.', 5),
(103, 9, 'Opens cans smoothly every time. No sharp edges left.', 3),
(103, 38, 'Easy to clean. Compact design stores easily.', 4),
(104, 23, 'Perfect for camping trips! Comfortable and easy to set up.', 5),
(104, 61, 'Tree straps are strong and don''t damage bark. Carrying bag is durable.', 5),
(105, 30, 'Steam is fine and consistent. Helps with deep cleansing.', 4),
(105, 12, 'Portable size is great for travel. Two steam settings are enough.', 5),
(106, 54, 'Dries wet shoes overnight! Deodorizer function works well.', 5),
(106, 7, 'Works for boots and regular shoes. Timer function is useful.', 5),
(107, 42, 'Accurate weight readings. Backlit display helps in dim light.', 5),
(107, 25, 'Compact for travel. Easy to use with one hand.', 4),
(108, 65, 'Perfect single-serving waffles! Heats up quickly.', 5),
(108, 18, 'Non-stick surface works well. Easy to clean.', 5),
(109, 51, 'Fits my car windshield perfectly. Reflects heat effectively.', 5),
(109, 34, 'Folds compactly into storage bag. Easy to put up and take down.', 5),
(110, 14, 'Works as both hand warmer and power bank! Smart dual function.', 5),
(110, 47, 'Three heat settings are perfect for different weather conditions.', 5),
(111, 28, 'Magnetic jars stick securely to fridge. Labels are clear.', 5),
(111, 3, 'Organized my spice cabinet perfectly. Jars are uniform size.', 5),
(112, 60, 'Reaches those impossible itchy spots! Extends to good length.', 5),
(112, 21, 'Multiple scratching surfaces feel great. Compact storage.', 4),
(113, 36, 'Improves my swing with real-time feedback. App tracks progress well.', 5),
(113, 49, 'Accurate swing analysis. Easy to attach to any club.', 5),
(114, 5, 'Feeds my fish reliably while on vacation. Adjustable portion size.', 5),
(114, 52, 'Easy to program. Battery backup keeps settings during power outage.', 5),
(115, 11, 'Reduces morning puffiness effectively. Feels refreshing on skin.', 5),
(115, 64, 'Reusable and easy to clean. Stays cold long enough for full facial massage.', 4),
(116, 27, 'Helps my baby sleep through noise. Multiple sound options.', 5),
(116, 40, 'Portable for travel. Battery lasts all night.', 5),
(117, 8, 'Grows herbs successfully indoors! LED lights are energy efficient.', 5),
(117, 55, 'Fresh herbs year-round. Water level indicator is helpful.', 5),
(118, 31, 'Helps improve my posture at work. Breathable material is comfortable.', 4),
(118, 16, 'Adjustable straps provide custom fit. Noticeable difference in back alignment.', 5),
(119, 59, 'Opens wine bottles effortlessly. Rechargeable battery lasts long.', 5),
(119, 24, 'Foil cutter works smoothly. Fast charging via USB.', 5),
(120, 46, 'Privacy screen works as advertised. People can''t see my screen from sides.', 5),
(120, 13, 'Anti-glare helps in bright offices. Easy to install and remove.', 4),
(121, 33, 'Perfect for reading in bed. Adjustable to multiple comfortable angles.', 5),
(121, 50, 'Holds tablet securely. Well-made and sturdy.', 5),
(122, 6, 'Comprehensive emergency kit for car. Hope to never need it but glad to have it.', 5),
(122, 43, 'Well-organized with quality tools. First aid supplies are complete.', 5),
(123, 29, 'Holds cookbook at perfect angle. Tablet holder is bonus feature.', 5),
(123, 62, 'Page clips work well. Adjustable height is useful.', 4),
(124, 17, 'Low latency is perfect for competitive gaming. Surround sound is immersive.', 5),
(124, 54, 'Comfortable for long sessions. Battery life exceeds advertised time.', 5),
(125, 2, 'Tracks my water intake accurately. Reminders help me stay hydrated.', 5),
(125, 39, 'Temperature display is accurate. Easy to clean.', 5),
(126, 22, 'Cools my small office effectively. Remote control works from across room.', 4),
(126, 57, 'Dehumidifier function works well in humid climates. Easy to drain tank.', 5),
(127, 10, 'Converts my regular desk perfectly. Memory presets save time.', 5),
(127, 35, 'Sturdy construction. Smooth height adjustment.', 5),
(128, 48, 'Immersive VR experience! Room-scale tracking works perfectly.', 5),
(128, 23, 'Controllers are intuitive. Graphics are stunning.', 5),
(129, 63, 'Discreet fitness tracking. Sleep monitoring is surprisingly accurate.', 5),
(129, 18, 'Battery lasts 5-6 days. Syncs well with health apps.', 5),
(130, 41, 'Powerful suction for pet hair. Multiple attachments handle all surfaces.', 5),
(130, 26, 'Easy to empty dust bin. Wall mount charging is convenient.', 5),
(131, 7, '25-mile range is accurate. Folds compactly for storage.', 5),
(131, 44, 'App shows battery status and tracks rides. Smooth acceleration.', 4),
(132, 15, 'Workout classes are high quality. Form feedback is helpful.', 5),
(132, 58, 'Looks like a regular mirror when off. Space-saving design.', 5),
(133, 30, 'Heats up quickly and maintains precise temperatures. Safety features are reassuring.', 5),
(133, 12, 'Energy efficient compared to gas stove. Easy to clean glass surface.', 5),
(134, 53, 'Blocks out snoring partner effectively! Comfortable for side sleeping.', 5),
(134, 20, 'White noise options help me fall asleep faster. Stays in ears well.', 4),
(135, 37, 'Perfect rice every time. Multiple cooking functions are useful.', 5),
(135, 4, 'Easy to clean inner pot. Pressure cooking is fast and efficient.', 5),
(136, 61, 'Customizable RGB lighting is beautiful. Mechanical switches feel great.', 5),
(136, 28, 'Macro keys help with productivity. Software is easy to use.', 5),
(137, 9, 'Second screen for my laptop on the go! Touchscreen is responsive.', 5),
(137, 46, 'USB-C provides both power and video. Bright enough for outdoor use.', 4),
(138, 19, 'Keyless entry is convenient. Fingerprint scanner is fast and accurate.', 5),
(138, 32, 'Auto-lock feature gives peace of mind. Installation was straightforward.', 5),
(139, 55, 'Smooth ride on various terrains. App control is intuitive.', 5),
(139, 14, '20-mile range is accurate even with hills. Fast charging.', 5),
(140, 49, 'Charges phone while providing large mouse surface. Non-slip bottom.', 5),
(140, 3, 'Stitched edges prevent fraying. Works with all wireless chargers.', 5),
(1, 12, 'Absolutely terrible! Stopped working after 2 weeks. Avoid!', 1),
(1, 23, 'Battery drains in 2 hours, not the advertised 20. False advertising.', 1),
(1, 34, 'Sound quality is mediocre at best. Overpriced.', 2),
(1, 45, 'Comfortable but sound leaks terribly. Everyone can hear my music.', 2),
(1, 56, 'Noise cancellation is non-existent. Can hear everything around me.', 1),
(1, 8, 'Great for the price! Better than expected.', 4),
(1, 19, 'Perfect for commuting. Blocks out subway noise completely.', 5),
(1, 30, 'Worth every penny. Best headphones under $100.', 5),
(1, 41, 'Good but not great. Expected better bass.', 3),
(1, 52, 'Broke after 3 months. Build quality is poor.', 1),
(1, 63, 'Excellent sound quality. Very comfortable for long sessions.', 5),
(1, 7, 'Charging port is loose. Difficult to charge now.', 2),
(1, 18, 'Good value for money. Does what it promises.', 4),
(1, 29, 'Microphone quality is terrible for calls.', 2),
(1, 40, 'Lightweight and comfortable. Perfect for workouts.', 5),
(1, 51, 'Connection drops frequently. Very frustrating.', 1),
(1, 62, 'Great product! Would buy again.', 5),
(1, 6, 'Average at best. Nothing special.', 3),
(1, 17, 'Ear cushions started peeling after 1 month.', 2),
(1, 28, 'Perfect for office use. Blocks out co-workers.', 5),
(1, 39, 'Bass is weak. Not for bass lovers.', 2),
(1, 50, 'Best purchase this year!', 5),

(2, 3, 'Battery lasts only 12 hours, not 24. Useless for sleep tracking.', 1),
(2, 14, 'Screen scratches easily. Needs a protector immediately.', 2),
(2, 25, 'Fitness tracking is inaccurate. Counts steps while driving.', 1),
(2, 36, 'Love it! Tracks my runs perfectly.', 5),
(2, 47, 'Water resistant claim is false. Died after getting caught in rain.', 1),
(2, 58, 'Good for basic notifications. Battery could be better.', 3),
(2, 9, 'Heart rate monitor is very accurate compared to chest strap.', 5),
(2, 20, 'GPS takes forever to lock. Annoying for runs.', 2),
(2, 31, 'Great smartwatch for the price!', 4),
(2, 42, 'App crashes constantly. Software needs work.', 1),
(2, 53, 'Comfortable to wear 24/7. Sleep tracking is useful.', 5),
(2, 64, 'Charging cable broke after 2 weeks. Cheap materials.', 1),
(2, 5, 'Does everything I need. Good value.', 4),
(2, 16, 'Screen is too dim in sunlight.', 2),
(2, 27, 'Perfect for tracking workouts and health metrics.', 5),
(2, 38, 'Syncing with phone is unreliable.', 2),
(2, 49, 'Best fitness tracker I have owned.', 5),
(2, 60, 'Overheats during charging. Concerned about safety.', 1),

-- Product 5: Mechanical Keyboard (15 reviews - popular with enthusiasts)
(5, 11, 'Keys stopped working after 1 month. Quality control issues.', 1),
(5, 22, 'Too loud for office environment. Colleagues complained.', 2),
(5, 33, 'Best typing experience ever! Worth every dollar.', 5),
(5, 44, 'RGB lighting failed in half the keys after 2 weeks.', 1),
(5, 55, 'Perfect for gaming. Responsive and comfortable.', 5),
(5, 2, 'Software is buggy. Can''t customize lighting properly.', 2),
(5, 13, 'Build quality is excellent. Very sturdy.', 5),
(5, 24, 'Cable is not detachable. Poor design choice.', 3),
(5, 35, 'Keys feel amazing. Love the tactile feedback.', 5),
(5, 46, 'Started double-typing letters after 3 months.', 1),
(5, 57, 'Great keyboard but too expensive.', 4),
(5, 4, 'Perfect for programming. Improves typing speed.', 5),
(5, 15, 'Spacebar rattles. Annoying sound.', 2),
(5, 26, 'Wrist rest is comfortable but collects dust.', 3),
(5, 37, 'Would buy again! Best keyboard under $150.', 5),

-- Product 8: Phone Case (12 reviews)
(8, 19, 'Phone broke despite using this case. Useless protection.', 1),
(8, 30, 'Kickstand broke first week. Flimsy construction.', 1),
(8, 41, 'Good protection. Survived multiple drops.', 5),
(8, 52, 'Adds too much bulk to phone.', 2),
(8, 63, 'Perfect case! Love the kickstand feature.', 5),
(8, 8, 'Buttons are hard to press through case.', 2),
(8, 29, 'Good value for money. Does the job.', 4),
(8, 50, 'Colors faded after 2 months.', 2),
(8, 7, 'Wireless charging works perfectly through case.', 5),
(8, 28, 'Camera cutout doesn''t align properly.', 1),
(8, 49, 'Best case I have owned. Thin yet protective.', 5),
(8, 6, 'Average case. Nothing special.', 3),

-- Product 11: Gaming Monitor (10 reviews - mixed quality)
(11, 21, 'Dead pixel right out of the box. Terrible quality control.', 1),
(11, 32, '144Hz is amazing for gaming. Smooth gameplay.', 5),
(11, 43, 'Backlight bleed is terrible. Very distracting in dark scenes.', 1),
(11, 54, 'Colors are vibrant. Great for both gaming and work.', 5),
(11, 1, 'Stand is wobbly. Monitor shakes when typing.', 2),
(11, 12, 'Worth every penny. Best monitor for gaming.', 5),
(11, 23, 'HDR is fake. Doesn''t work properly.', 1),
(11, 34, 'Excellent monitor! 1440p looks crisp.', 5),
(11, 45, 'Screen developed a line after 4 months.', 1),
(11, 56, 'Good monitor but speakers are terrible.', 3),

-- Products with very few reviews (unpopular items)
(13, 10, 'Cable kit is incomplete. Missing crucial pieces.', 2),
(13, 31, 'Works as advertised. Keeps desk tidy.', 4),

(14, 42, 'Fans are loud and ineffective. Laptop still overheats.', 1),

(67, 5, 'Too complicated to set up. Returned it.', 2),

(89, 18, 'Works well. Good basic product.', 4),

(112, 27, 'Does the job. Nothing fancy.', 3),

-- Products with mostly negative reviews
(120, 39, 'Privacy filter makes screen too dark. Can''t see anything.', 1),
(120, 50, 'Glare is worse with this filter. Useless.', 1),
(120, 61, 'Peels off easily. Doesn''t stick properly.', 1),
(120, 8, 'Works but reduces screen quality significantly.', 2),

(132, 19, 'Car vacuum has weak suction. Can''t pick up anything.', 1),
(132, 30, 'Battery lasts 5 minutes. Completely useless.', 1),
(132, 41, 'Cord is too short. Can''t reach back seats.', 1),
(132, 52, 'Broke after 2 uses. Cheap plastic construction.', 1),

(97, 63, 'Cleaning gel falls apart. Makes bigger mess.', 1),
(97, 10, 'Doesn''t pick up dust. Sticky residue left on keyboard.', 1),
(97, 21, 'Works once then loses stickiness.', 1),

-- Products with perfect 5-star reviews (premium items)
(127, 32, 'Best standing desk converter! Smooth adjustment.', 5),
(127, 43, 'Ergonomic game changer. No more back pain.', 5),
(127, 54, 'Sturdy construction. Holds dual monitors securely.', 5),
(127, 1, 'Memory presets work perfectly. Great for shared desks.', 5),
(127, 12, 'Worth the investment for home office.', 5),
(127, 23, 'Easy to assemble. Instructions were clear.', 5),
(127, 34, 'Perfect height range for tall and short users.', 5),
(127, 45, 'Quiet motor. Doesn''t disturb during calls.', 5),
(127, 56, 'Best purchase for WFH setup.', 5),

(136, 7, 'Mechanical keyboard is perfect for typing.', 5),
(136, 18, 'RGB lighting is beautiful. Customization is endless.', 5),
(136, 29, 'Build quality is premium. Worth the price.', 5),
(136, 40, 'Best keyboard I have ever used.', 5),
(136, 51, 'Improved my typing speed and accuracy.', 5),
(136, 62, 'Perfect for both work and gaming.', 5),

-- More reviews for mid-range products (3-4 stars)
(3, 13, 'Good laptop stand but could be more adjustable.', 3),
(3, 24, 'Sturdy aluminum. Does the job.', 4),
(3, 35, 'Helps with neck strain. Good value.', 4),
(3, 46, 'Lightweight and portable.', 4),
(3, 57, 'Rubber feet prevent sliding.', 4),

(4, 4, 'USB-C hub works well with my MacBook.', 4),
(4, 15, 'All ports work as expected.', 4),
(4, 26, 'Gets warm during extended use but still functional.', 3),
(4, 37, 'Compact design. Good for travel.', 4),
(4, 48, 'SD card reader is slow but works.', 3),

(6, 59, 'Fast transfer speeds as advertised.', 5),
(6, 16, 'Reliable portable storage.', 5),
(6, 27, 'Durable metal casing.', 5),
(6, 38, 'Small and lightweight.', 5),
(6, 49, 'Perfect for backing up photos.', 5),

(7, 60, 'Good webcam for the price.', 4),
(7, 17, 'Auto-focus works well.', 4),
(7, 28, 'Microphone quality is average.', 3),
(7, 39, 'Plug and play. Easy setup.', 4),
(7, 50, 'Better than built-in laptop camera.', 4),

(9, 7, 'Waterproof feature works! Survived pool party.', 5),
(9, 18, 'Good sound quality for size.', 4),
(9, 29, 'Battery life is excellent.', 5),
(9, 40, 'Not very loud for outdoor parties.', 3),
(9, 51, 'Bluetooth range is good.', 4),

(10, 62, 'Comfortable wireless mouse.', 5),
(10, 9, 'Battery lasts months.', 5),
(10, 20, 'DPI adjustment is useful.', 4),
(10, 31, 'Works on glass surfaces.', 5),
(10, 42, 'Scroll wheel started squeaking after 6 months.', 2),

-- Additional negative reviews for balance
(12, 53, 'LED lamp flickers. Poor quality.', 1),
(12, 64, 'Touch controls are unresponsive.', 1),
(12, 11, 'USB charging port stopped working.', 1),

(15, 22, 'Office chair assembly took 3 hours. Missing parts.', 1),
(15, 33, 'Wheels don''t roll smoothly on carpet.', 2),
(15, 44, 'Lumbar support is uncomfortable.', 2),

(22, 55, 'Wireless charger overheats phone dangerously.', 1),
(22, 2, 'Charging speed is slow.', 2),

(31, 13, 'Digital thermometer is inaccurate by 10 degrees.', 1),
(31, 24, 'App disconnects constantly.', 1),

(45, 35, 'Reusable bags leak. Not airtight.', 1),
(45, 46, 'Silicone picks up food odors.', 2),

(58, 57, 'Posture corrector is uncomfortable to wear.', 1),
(58, 4, 'Straps dig into shoulders.', 1),

(73, 15, 'Magnetic mount lost strength in cold weather.', 2),
(73, 26, 'Phone fell off while driving. Dangerous.', 1),

(86, 37, 'Nail file kit broke during first use.', 1),
(86, 48, 'Attachments don''t stay secure.', 1),

(99, 59, 'Waterproof pouch leaked. Phone damaged.', 1),
(99, 16, 'Touchscreen doesn''t work through pouch.', 2),

-- Some products with single reviews
(105, 27, 'Facial steamer works well. Good mist output.', 4),
(116, 38, 'White noise machine helps baby sleep.', 5),
(128, 49, 'VR headset is incredible. Immersive experience.', 5),
(139, 60, 'Electric skateboard is fun but range is overestimated.', 3),
(21, 17, 'Gaming headset mic quality is poor.', 2),
(34, 28, 'Electric wine opener works smoothly.', 5),
(47, 39, 'Car jump starter saved me twice already.', 5),
(52, 50, 'Digital drawing tablet is great for beginners.', 4),
(68, 61, 'Smart light bulbs lose connection frequently.', 2),
(79, 8, 'Plant monitor is accurate and helpful.', 5),
(93, 29, 'Car seat gap filler is perfect organizer.', 5),
(107, 40, 'Luggage scale is accurate and easy to use.', 4),
(118, 51, 'Cordless drill is powerful for DIY projects.', 5),
(129, 62, 'Smart ring tracks sleep accurately.', 4),
(21, 9, 'Surround sound is immersive but mic quality is bad.', 3),
(35, 20, 'Gaming mouse pad is huge and perfect.', 5),
(49, 31, 'Phone tripod is sturdy and adjustable.', 4),
(63, 42, 'Electric back massager is too weak.', 2),
(77, 53, 'UV sanitizer gives peace of mind.', 5),
(91, 64, 'Water flosser is powerful and effective.', 5),
(104, 11, 'Camping hammock is comfortable and durable.', 5),
(117, 22, 'Indoor herb garden grows basil well.', 4),
(130, 33, 'Cordless vacuum is powerful for pet hair.', 5),
(21, 44, 'Headset comfortable but mic issues.', 3),
(38, 55, 'Bluetooth car adapter has static noise.', 2),
(55, 2, 'Professional mic is studio quality.', 5),
(72, 13, 'Adjustable dumbbells are space-saving.', 5),
(88, 24, 'Portable espresso maker makes great coffee.', 4),
(103, 35, 'Automatic can opener works every time.', 5),
(119, 46, 'Electric wine opener is convenient.', 5),
(21, 57, 'Gaming headset audio is good but mic terrible.', 2),
(40, 4, 'Multi-port charging station charges all devices fast.', 5),
(61, 15, 'Smart light bulbs work with Google Home.', 5),
(82, 26, 'Posture corrector helps with back pain.', 4),
(98, 37, 'Controller charger dock is convenient.', 5),
(115, 48, 'Ice roller reduces puffiness effectively.', 4),
(21, 59, 'Would not recommend due to mic issues.', 2),
(44, 16, 'Car vacuum is weak but okay for light cleaning.', 3),
(69, 27, 'Resistance bands are good for home workouts.', 4),
(94, 38, 'Memory foam cushion is comfortable.', 5),
(110, 49, 'Hand warmer/power bank is dual-function genius.', 5),
(21, 60, 'Third pair with same mic problem. Quality control issue.', 1),
(50, 17, 'Sunglasses are stylish with good UV protection.', 4),
(75, 28, 'Folding water bottle is perfect for travel.', 5),
(100, 39, 'Automatic pet feeder works perfectly.', 5),
(21, 50, 'Company refuses to replace defective headset.', 1),
(56, 7, 'Keyboard cleaning gel is fun and effective.', 5),
(81, 18, 'Silicone food bags are eco-friendly.', 4),
(106, 29, 'Shoe dryer works quickly.', 5),
(21, 40, 'DO NOT BUY! Mic stops working after 2 weeks consistently.', 1),
(65, 51, 'Gaming controller charger is reliable.', 5),
(90, 62, 'Himalayan salt lamp creates relaxing ambiance.', 5);





-- Insert more product reviews
INSERT INTO product_reviews (product_id, user_id, text, score) VALUES
(15, 6, 'Life-changing chair! My back pain is gone after switching to this.', 5),
(15, 7, 'Great chair, but assembly took longer than expected.', 4),
(15, 8, 'Worth every penny. Adjustable features make it perfect for long work days.', 5),
(16, 6, 'Amazing noise cancellation. Perfect for flights and busy offices.', 5),
(16, 9, 'Good sound quality but case is a bit bulky.', 4),
(16, 10, 'Battery life is excellent. Lasts through my entire workday.', 5),
(17, 7, 'Incredible video quality. Perfect for my hiking adventures.', 5),
(17, 8, 'Easy to use but stabilization could be better during fast movement.', 4),
(18, 6, 'Best purchase for my home office. Switching positions helps so much.', 5),
(18, 9, 'Very sturdy desk. Installation was straightforward.', 5),
(18, 10, 'Motor is quiet and smooth. Memory presets work perfectly.', 5),
(19, 7, 'Works with all my smart devices. Setup was simple.', 5),
(19, 8, 'Good hub but wish it had Zigbee support.', 3),
(20, 9, 'Game changer for productivity. The extra screen space is amazing.', 5),
(20, 6, 'Perfect for coding and gaming. Curved screen is immersive.', 5),
(20, 7, 'Great monitor but takes up a lot of desk space.', 4),
(21, 8, 'Comfortable for long gaming sessions. Mic quality is clear.', 5),
(21, 10, 'Good headset but ear cups get warm after a while.', 4),
(22, 9, 'Charges my phone quickly. Simple and effective.', 5),
(22, 6, 'Works through my phone case. Very convenient.', 5),
(23, 7, 'Saved my phone multiple times on trips. Fast charging works well.', 5),
(23, 8, 'Heavy but reliable. Charges my laptop and phone.', 4),
(24, 9, 'Scans are crystal clear. Great for digitizing old documents.', 5),
(24, 10, 'ADF works smoothly. Software is user-friendly.', 5),
(25, 6, 'Peace of mind while driving. Footage is very clear.', 5),
(25, 7, 'Installation was tricky but worth it. Parking mode is great.', 4),
(26, 8, 'Noticeable difference in air quality. Quiet operation.', 5),
(26, 9, 'Reduces allergens. Smart sensors work accurately.', 5),
(27, 10, 'Love seeing who is at the door from my phone. Installation was easy.', 5),
(27, 6, 'Good video quality but motion detection is too sensitive.', 4),
(28, 7, 'Cleans thoroughly and returns to base automatically. Time saver!', 5),
(28, 8, 'Mapping feature is accurate. Much better than random cleaning.', 5);



